### ISSUE TITLE
主页中课程是否需要分板块来做一下分类

### ISSUE THREAD

**Issue by siyuanluo** [conanhujinming/comments-for-awesome-courses#13]
两种方式：
1. 是否可以按照CSranking网站的形式来进行对不同领域课程的划分，这样会更易于检索（抱着对网课学习的目的来查看此Project）；
2. 或者也可以按照学校来进行划分（抱着检索的态度来查看此Project）

ps.个人更推荐第一种分类方式

**Comment by conanhujinming** [comment]
嗯，可以分一下类的，我回头看看怎么操作一下。

**Comment by conanhujinming** [comment]
已根据我个人对这些课程的认识进行分类。
